package com.example.codeverse.Students.Activities;

import android.app.Dialog;
import android.content.Context;
import android.content.Intent;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;
import com.airbnb.lottie.LottieAnimationView;
import com.example.codeverse.Students.Models.Exam;
import com.example.codeverse.R;
import com.google.android.material.button.MaterialButton;

public class AdmitCardDialog {
    private Context context;
    private Dialog dialog;
    private Exam exam;

    public AdmitCardDialog(Context context, Exam exam) {
        this.context = context;
        this.exam = exam;
        createDialog();
    }

    private void createDialog() {
        dialog = new Dialog(context);
        dialog.setContentView(R.layout.dialog_admission_card);
        dialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        setupViews();
    }

    private void setupViews() {
        TextView tvSubject = dialog.findViewById(R.id.tv_subject);
        TextView tvExamType = dialog.findViewById(R.id.tv_exam_type);
        TextView tvDate = dialog.findViewById(R.id.tv_date);
        TextView tvTime = dialog.findViewById(R.id.tv_time);
        TextView tvVenue = dialog.findViewById(R.id.tv_venue);
        TextView tvStudentName = dialog.findViewById(R.id.tv_student_name);
        TextView tvStudentId = dialog.findViewById(R.id.tv_student_id);

        ImageButton btnClose = dialog.findViewById(R.id.btn_close);
        MaterialButton btnShare = dialog.findViewById(R.id.btn_share);
        LottieAnimationView btnSave = dialog.findViewById(R.id.btn_save);

        if (tvSubject != null) tvSubject.setText(exam.getSubjectName());
        if (tvExamType != null) tvExamType.setText(exam.getExamType());
        if (tvDate != null) tvDate.setText(exam.getExamDate());
        if (tvTime != null) tvTime.setText(exam.getStartTime() + " - " + exam.getEndTime());
        if (tvVenue != null) tvVenue.setText(exam.getRoom());
        if (tvStudentName != null) tvStudentName.setText("John Doe");
        if (tvStudentId != null) tvStudentId.setText("S12345678");

        if (btnClose != null) {
            btnClose.setOnClickListener(v -> dialog.dismiss());
        }

        if (btnShare != null) {
            btnShare.setOnClickListener(v -> shareAdmitCard());
        }

        if (btnSave != null) {
            btnSave.setOnClickListener(v -> saveAdmitCard());
        }
    }

    private void shareAdmitCard() {
        try {
            Intent shareIntent = new Intent(Intent.ACTION_SEND);
            shareIntent.setType("text/plain");
            shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Admission Card - " + exam.getSubjectName());
            shareIntent.putExtra(Intent.EXTRA_TEXT, buildAdmissionCardText());
            context.startActivity(Intent.createChooser(shareIntent, "Share Admission Card"));
        } catch (Exception e) {
            Toast.makeText(context, "Error sharing admission card", Toast.LENGTH_SHORT).show();
        }
    }

    private String buildAdmissionCardText() {
        return "🎓 ADMISSION CARD 🎓\n\n" +
                "📚 Subject: " + exam.getSubjectName() + "\n" +
                "📋 Exam Type: " + exam.getExamType() + "\n" +
                "📅 Date: " + exam.getExamDate() + "\n" +
                "⏰ Time: " + exam.getStartTime() + " - " + exam.getEndTime() + "\n" +
                "🏛️ Venue: " + exam.getRoom() + "\n" +
                "👤 Student: John Doe\n" +
                "🆔 ID: S12345678\n\n" +
                "⚠️ Mandatory to have to go to examination hall\n" +
                "Generated by CodeVerse Exam System";
    }

    private void saveAdmitCard() {
        Toast.makeText(context, "Admission card saved successfully!", Toast.LENGTH_SHORT).show();
        dialog.dismiss();
    }

    public void show() {
        if (dialog != null) {
            dialog.show();
        }
    }

    public void dismiss() {
        if (dialog != null && dialog.isShowing()) {
            dialog.dismiss();
        }
    }
}